services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - animexchange-network
    volumes:
      - zookeeper-data:/var/lib/zookeeper

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - animexchange-network
    volumes:
      - kafka-data:/var/lib/kafka

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 4000:4000
    networks:
      - animexchange-network
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      KAFKA_BROKER_URL: ${KAFKA_BROKER_URL}
    depends_on:
      - kafka
      - postgres

  marketplace-service:
    build:
      context: ./services/marketplace-service
      dockerfile: Dockerfile
    container_name: marketplace-service
    networks:
      - animexchange-network
    environment:
      KAFKA_BROKER_URL: kafka:9092
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - kafka
      - postgres

  nft-service:
    build:
      context: ./services/nft-service
      dockerfile: Dockerfile
    container_name: nft-service
    networks:
      - animexchange-network
    environment:
      KAFKA_BROKER_URL: kafka:9092
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - kafka
      - postgres

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: user-service
    networks:
      - animexchange-network
    environment:
      KAFKA_BROKER_URL: kafka:9092
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - kafka
      - postgres

  wallet-service:
    build:
      context: ./services/wallet-service
      dockerfile: Dockerfile
    container_name: wallet-service
    networks:
      - animexchange-network
    environment:
      KAFKA_BROKER_URL: kafka:9092
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - kafka
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - animexchange-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  animexchange-network:
    driver: bridge

volumes:
  zookeeper-data:
  kafka-data:
  postgres-data:
