services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - kafka-network

  gateway:
    build: ./apps/api
    container_name: gateway
    depends_on:
      - kafka
      - auth
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
    networks:
      - kafka-network

  auth:
    build: ./services/auth
    container_name: auth
    depends_on:
      - kafka
    environment:
      AUTH_PORT: 5001
      JWT_SECRET: "your-secret-key"
    ports:
      - "5001:5001"
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
